name: make-kml
on:
schedule:
- cron:  10 0 1 * *

jobs:
  release:
    name: make-kml
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: make-kml
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GCLOUD_API_KEY: ${{ secrets.GCLOUD_API_KEY }}
        TZ: 'Asia/Tokyo'
      run: .github/actions/make-kml.sh
