---
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/legnoh/wlw-locate-kml.git
  - name: month1st-7am
    type: cron-resource
    source:
      expression: "10 7 1 * *"
      location: Asia/Tokyo
      fire_immediately: true
  - name: release
    type: github-release
    source:
      owner: concourse
      repository: concourse
      access_token: ((github-access-token))
      pre_release: true
  - name: slack
    type: slack-notification
    source:
      url: ((slack-url))

jobs:
- name: make-kml
  public: true
  plan:
  - get: repo
  - get: month1st-7am
    trigger: true
  - task: make-kml
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repo
      outputs:
        - name: out
      run:
        path: repo/ci/run.sh
  - put: release
    params:
      name: out/name
      tag: out/tag
      body: out/body
      globs:
      - out/result-*.kml
      predefined_acl: publicRead
      content_type: application/octet-stream
  on_success:
    put: slack
    params:
      text: |
        @legnoh wlw-locate-kml is updated:tea:
        https://github.com/legnoh/wlw-locate-kml/releases
        $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  on_failure:
    put: slack
    params:
      text: |
        @legnoh wlw-locate-kml failed:bomb:
        $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
