---
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/legnoh/wlw-locate-kml.git
  - name: month1st-7am
    type: cron-resource
    source:
      expression: "10 7 1 * *"
      location: Asia/Tokyo
  - name: release
    type: github-release
    source:
      owner: legnoh
      repository: wlw-locate-kml
      access_token: ((github-access-token))
      release: false
      pre_release: true
  - name: slack
    type: slack-notification
    source:
      url: ((slack-url))
  - name: tweet
    type: twitter
    source:
      consumer_key: ((twitter-consumer-key))
      consumer_secret: ((twitter-consumer-secret))
      access_token: ((twitter-access-token))
      access_token_secret: ((twitter-access-token-secret))

jobs:
- name: make-kml
  public: true
  build_logs_to_retain: 12
  plan:
  - get: repo
  - get: month1st-7am
    trigger: true
  - task: make-kml
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
        - name: repo
      outputs:
        - name: out
      run:
        path: repo/ci/run.sh
      params:
        TZ: 'Asia/Tokyo'
  - put: release
    params:
      name: out/name
      tag: out/tag
      body: out/body
      globs:
      - out/result-*.kml
      predefined_acl: publicRead
      content_type: application/octet-stream
  on_success:
    put: slack
    params:
      text: |
        新しいKMLができたよ!:christmas_tree:
        https://github.com/legnoh/wlw-locate-kml/releases
        $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  on_failure:
    put: slack
    params:
      text: |
        KML作りに失敗したんだよ...:fire::fire:
        $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
- name: post-tweet
  public: true
  plan:
  - get: release
    passed: ["make-kml"]
  - put: tweet
    params:
      status: |
        ワンダーMAPを更新しました。変更点はdiffを確認ください。 #sega_wlw
        https://github.com/legnoh/wlw-locate-kml/releases
        https://www.google.com/maps/d/viewer?hl=ja&mid=1ENDxk6QqlKlyjqS4iB_1HNyD7UM

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: twitter
  type: docker-image
  source:
    repository: ecsteam/twitter-concourse-resource
