name: tweet
on:
  release:
    types: [edited]

jobs:
  publish_tweet:
    name: tweet
    runs-on: ubuntu-latest
    steps:
      - name: update
        uses: xorilog/twitter-action@0.1
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_MESSAGE: |
            ワンダーMAPを更新しました。変更点はdiffを確認ください。 #sega_wlw
            https://github.com/legnoh/wlw-locate-kml/releases
            https://www.google.com/maps/d/viewer?hl=ja&mid=1ENDxk6QqlKlyjqS4iB_1HNyD7UM
